export const routes = {
  login: "/login",

  dashboard: "/dashboard",
  monitoring: "/monitoring",
  decisionCenter: "/decision",
  analytics: "/analytics",
  assets: "/assets",
  apiManagement: "/api-management",
  aiRecommendations: "/ai-recommendations",
  reports: "/reports",
  organization: "/organization",
  organizationUsers: "/organization/users",
  organizationSessions: "/organization/sessions",
  organizationPolicy: "/organization/policy",
  organizationAuditLog: "/organization/audit-log",
  notifications: "/notifications",
  settings: "/settings",
  profile: "/profile",
} as const;
