"use client"

import { Skeleton } from "@/components/ui/skeleton"
import { useRecommendations } from "./hooks/useRecommendations"
import RecommendationCard from "./components/RecommendationCard"

const ViewRecommendations = () => {
  const { data, isLoading, isError } = useRecommendations()

  if (isLoading) {
    return (
      <div className="flex w-full flex-col gap-6">
        <Skeleton className="h-7 w-48" />
        <Skeleton className="h-7 w-72" />
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
          {Array.from({ length: 3 }).map((_, i) => (
            <Skeleton key={i} className="h-52 w-full rounded-xl" />
          ))}
        </div>
      </div>
    )
  }

  if (isError) {
    return (
      <div className="flex w-full flex-col gap-6">
        <h1 className="text-xl font-bold text-card-foreground">AI Recommendations</h1>
        <p className="text-destructive">Failed to load recommendations. Please try again later.</p>
      </div>
    )
  }

  if (!data) return null

  return (
    <div className="flex w-full flex-col gap-6">
      <div>
        <h1 className="text-xl font-bold text-card-foreground">AI Recommendations</h1>
        <p className="text-sm text-muted-foreground">
          Actionable insights generated by AI analysis
        </p>
      </div>
      <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
        {data.recommendations.map((rec) => (
          <RecommendationCard key={rec.id} recommendation={rec} />
        ))}
      </div>
    </div>
  )
}

export default ViewRecommendations
