"use client"

import { PageHeader } from "@/components/shared/PageHeader"
import { useRecommendations } from "./hooks/useRecommendations"
import RecommendationCard from "./components/RecommendationCard"
import RecommendationsSkeleton from "./components/RecommendationsSkeleton"

const ViewRecommendations = () => {
  const { data, isLoading, isError } = useRecommendations()

  if (isLoading) {
    return <RecommendationsSkeleton />
  }

  if (isError) {
    return (
      <div className="flex w-full flex-col gap-6">
        <h1 className="text-xl font-bold text-card-foreground">AI Recommendations</h1>
        <p className="text-destructive">Failed to load recommendations. Please try again later.</p>
      </div>
    )
  }

  if (!data) return null

  return (
    <div className="flex w-full flex-col gap-6">
      <PageHeader
        title="AI Recommendations"
        subtitle="Actionable insights generated by AI analysis"
      />
      <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
        {data.recommendations.map((rec) => (
          <RecommendationCard key={rec.id} recommendation={rec} />
        ))}
      </div>
    </div>
  )
}

export default ViewRecommendations
